name: APOD Infra - Create AKS Cluster

on:
  workflow_dispatch:
    inputs:
      rg:
        description: "Resource Group"
        required: true
        default: 'ecs-c3'

env:
  RG_NAME: ${{ github.event.inputs.rg }}
  AKS_NAME: ${{ github.event.inputs.rg }}-aks
  ARGOCD_VERSION: v1.8.1

jobs:
  create-aks:
    runs-on: ubuntu-latest
    steps:

    - name: Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Checkout
      uses: actions/checkout@v2

    - name: Create cluster
      working-directory: scripts
      run: chmod +x aks-create.sh && ./aks-create.sh
      env:
        AKS_SP_APP_ID: ${{ secrets.AKS_SP_APP_ID }}
        AKS_SP_APP_PASSWORD: ${{ secrets.AKS_SP_APP_PASSWORD }}

    - name: Deploy Argo
      working-directory: scripts
      run: chmod +x argocd-deploy.sh && ./argocd-deploy.sh

    - name: Sync APOD app 
      working-directory: scripts
      run: chmod +x argocd-create-apod-app.sh && ./argocd-create-apod-app.sh
